# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dbbd718fd642f13b1848f99470e07959ee9cf88332beceb8fac6e9c8d9d817be2203ed692b535e891c2b722a500a4d936a1313a22295586a3c95e2cf3bb2a47e

test:
  secret_key_base: f4e81fc6726bd6e89249f22d04beca42f9f1705c267d70d0cbbc8d04a85006c05adcb4a12ac0236c1389836babff04d9d69aa9a757c61128edbc39ca215d9ae8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
